env:
  global:
    - coverage=false
    - CC_TEST_REPORTER_ID=f4be619f64012832252ac47ada6732017a9415075d3984f7d5db060a313f9a04

language: php

matrix:
  include:
  - php: 7.1
    env: coverage=true
  - php: 7.2
  - php: 7.3
  - php: 7.4

sudo: false

install:
    - composer install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - if [[ $coverage = 'true' ]]; then ./cc-test-reporter before-build; fi

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml

after_script:
    - if [[ $coverage = 'true' ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
